### ISSUE TITLE
Custom exceptions

### ISSUE THREAD

**Issue by nohe427** [SyndicateFighter/ArcMonsters-monsters#13]
Would be nice to implement custom exceptions into the player class so if user alive status is false, it cannot have its HP changed.  Will need to research custom exceptions and then write the unit tests for them.

**Comment by nohe427** [comment]
We will need to implement custom exceptions so that way if something happens that cannot happen, it will be appropriately handled by the battle engine and won't break the game.

**Comment by nohe427** [comment]
![git](https://cloud.githubusercontent.com/assets/3211589/11320376/cd90a17e-9064-11e5-95ec-7bd6011f22a0.png)

Via http://xkcd.com/1597/

**Comment by yuan8014** [comment]
You mean worker class, right? Totally agree with having custom exceptions! Would be very cool! Just the example you mentioned, situation of worker alive status becoming false, to me it sounds more like part of the normal workflow we can control, rather than exception...

**Comment by nohe427** [comment]
Right, I mean worker class.  Whoops!

**Comment by nohe427** [comment]
Do this in skill class and check other classes to add it.

**Comment by nohe427** [comment]
http://stackoverflow.com/questions/2190161/difference-between-java-lang-runtimeexception-and-java-lang-exception 

We want to do runtime exceptions.
