### ISSUE TITLE
alex update the jit pack

### ISSUE THREAD

**Issue by zxwandrew** [SyndicateFighter/ArcMonsters-monsters#37]
see title

**Comment by nohe427** [comment]
Going to go through and do a manual merge of Yuans PR and then update...

**Comment by nohe427** [comment]
@zxwandrew @andr7430 

JitPack can now be updated to:

compile 'com.github.SyndicateFighter:ArcMonsters-monsters:0.1.5'

**Comment by zxwandrew** [comment]
sweeeet :sweet_potato:
